### ISSUE TITLE
Why have Chrome and Chromium installed simultanously?

### ISSUE THREAD

**Issue by jobukkit** [endlessm/eos-browser-tools#16]
They are 99% the same program. Users are going to be confused why their history, bookmarks and settings are split between them.

**Comment by wjt** [comment]
Historically, Chromium was preinstalled as part of the OS itself; but we wanted to make Chrome (appear to) be the default browser for familiarity.

Nowadays, all Endless OS systems ship with only Chromium preinstalled (via Flatpak).
